[package]
name = "quokkadb"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
regex = "1.11.1"
crc32fast = "1.4.2"
crossbeam = "0.8.4"
crossbeam-skiplist = "0.1"
once_cell = "1.20.2"
bson = "2.13.0"
snap = "1.1"
lz4 = "1.24"
moka = { version = "0.12", features = ["sync"] }
tracing = "0.1.41"
arc-swap = "1.7.1"
tracing-subscriber = "0.3.19"

[dev-dependencies]
tempfile = "3.19.1"